[dev]
	publish="src"
[build]
	functions="functions"


[[redirects]]
	from="/editor"
	to="/"
	status=300
	force=true

[[redirects]]
	from="/editor.html"
	to="/"
	status=300
	force=true

[[redirects]]
	from="/createContributor"
	to="/.netlify/functions/createContributor"
	status=200

[[redirects]]
	from="/submitNote"
	to="/.netlify/functions/submitNote"
	status=200

[[redirects]]
	from="/login"
	to="/.netlify/functions/loginInit"
	status=200
