[dev]
	publish="src"
[build]
	functions="functions"

[[redirects]]
	from="/jpt"
	to="/"

[[redirects]]
	from="/editor"
	to="/"

[[redirects]]
	from="/editor.html"
	to="/"

[[redirects]]
	from="/createContributor"
	to="/.netlify/functions/createContributor"
	status=200

[[redirects]]
	from="/submitNote"
	to="/.netlify/functions/submitNote"
	status=200